name: CBolao
version: '${project.version}'
main: com.coopas.cbolao.Main
authors: [ Coopas ]
description: Plugin de evento de chat Bolão
website: https://github.com/coopas
depend: [ Vault ]
commands:
  bolao:
